version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - redis
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
    command: yarn start
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
    networks:
      - mynetwork

networks:
  mynetwork:
