version: '3.8'
services:
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
